#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncModeToDataHandler
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Books")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertsrcbooks(srcbooks instance);
    partial void Updatesrcbooks(srcbooks instance);
    partial void Deletesrcbooks(srcbooks instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::AsyncModeToDataHandler.Properties.Settings.Default.BooksConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<srcbooks> srcbooks
		{
			get
			{
				return this.GetTable<srcbooks>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.srcbooks")]
	public partial class srcbooks : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _code;
		
		private System.Nullable<int> _new;
		
		private string _name;
		
		private System.Nullable<decimal> _price;
		
		private string _izd;
		
		private System.Nullable<int> _npages;
		
		private string _format;
		
		private string _dateizd;
		
		private System.Nullable<int> _pressrun;
		
		private string _themes;
		
		private string _category;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodeChanging(System.Nullable<int> value);
    partial void OncodeChanged();
    partial void OnnewChanging(System.Nullable<int> value);
    partial void OnnewChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OnizdChanging(string value);
    partial void OnizdChanged();
    partial void OnnpagesChanging(System.Nullable<int> value);
    partial void OnnpagesChanged();
    partial void OnformatChanging(string value);
    partial void OnformatChanged();
    partial void OndateizdChanging(string value);
    partial void OndateizdChanged();
    partial void OnpressrunChanging(System.Nullable<int> value);
    partial void OnpressrunChanged();
    partial void OnthemesChanging(string value);
    partial void OnthemesChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    #endregion
		
		public srcbooks()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="Int")]
		public System.Nullable<int> code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="new", Storage="_new", DbType="Int")]
		public System.Nullable<int> @new
		{
			get
			{
				return this._new;
			}
			set
			{
				if ((this._new != value))
				{
					this.OnnewChanging(value);
					this.SendPropertyChanging();
					this._new = value;
					this.SendPropertyChanged("@new");
					this.OnnewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(170)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_izd", DbType="VarChar(50)")]
		public string izd
		{
			get
			{
				return this._izd;
			}
			set
			{
				if ((this._izd != value))
				{
					this.OnizdChanging(value);
					this.SendPropertyChanging();
					this._izd = value;
					this.SendPropertyChanged("izd");
					this.OnizdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_npages", DbType="Int")]
		public System.Nullable<int> npages
		{
			get
			{
				return this._npages;
			}
			set
			{
				if ((this._npages != value))
				{
					this.OnnpagesChanging(value);
					this.SendPropertyChanging();
					this._npages = value;
					this.SendPropertyChanged("npages");
					this.OnnpagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format", DbType="VarChar(15)")]
		public string format
		{
			get
			{
				return this._format;
			}
			set
			{
				if ((this._format != value))
				{
					this.OnformatChanging(value);
					this.SendPropertyChanging();
					this._format = value;
					this.SendPropertyChanged("format");
					this.OnformatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateizd", DbType="VarChar(16)")]
		public string dateizd
		{
			get
			{
				return this._dateizd;
			}
			set
			{
				if ((this._dateizd != value))
				{
					this.OndateizdChanging(value);
					this.SendPropertyChanging();
					this._dateizd = value;
					this.SendPropertyChanged("dateizd");
					this.OndateizdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pressrun", DbType="Int")]
		public System.Nullable<int> pressrun
		{
			get
			{
				return this._pressrun;
			}
			set
			{
				if ((this._pressrun != value))
				{
					this.OnpressrunChanging(value);
					this.SendPropertyChanging();
					this._pressrun = value;
					this.SendPropertyChanged("pressrun");
					this.OnpressrunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_themes", DbType="VarChar(60)")]
		public string themes
		{
			get
			{
				return this._themes;
			}
			set
			{
				if ((this._themes != value))
				{
					this.OnthemesChanging(value);
					this.SendPropertyChanging();
					this._themes = value;
					this.SendPropertyChanged("themes");
					this.OnthemesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="VarChar(60)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
